version: '3'

services:
  microservice2:
    build:
      context: .
    ports:
      - "3002:3002"
    environment:
      - POSTGRES_HOST=postgres  # Replace with your actual Postgres container name or IP
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    depends_on:
      - postgres
    # Add other configurations as needed

  postgres:
    image: postgres:9.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    # Add other configurations as needed
